### PR TITLE
Feature/use new segments shapefile

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Update for importing the new NIH shapefiles.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
(Tests pass locally, whatever Travis might say.)

**Comment by flibbertigibbet** [comment]
Note: once this is in, it will be necessary to use the new shapefiles, due to changes in the data types between the two shapefile sets.

**Comment by CloudNiner** [comment]
So we just need to move the new shapefiles into place and re-provision correct?

**Comment by CloudNiner** [comment]
Again, my java-foo is a bit weak, but this all looks pretty straightforward. +1

**Comment by flibbertigibbet** [comment]
Yes, just re-provision with the new shapefiles (assuming provision will overwrite existing files of the same name).

**Pull request merged**
